easy_admin:
  site_name: 'No Agenda Player Administration Panel'
  entities:
    Episode:
      class: App\Entity\Episode
      form:
        fields:
          - { property: 'code', type: 'text' }
          - { property: 'name', type: 'text' }
          - { property: 'author', type: 'text' }
    ChatMessage:
      class: App\Entity\ChatMessage
      form:
        fields:
          - { property: 'username', type: 'text' }
          - { property: 'contents', type: 'textarea' }
    BatSignal:
      class: App\Entity\BatSignal
      form:
        fields:
          - { property: 'code', type: 'text' }
          - { property: 'processed', type: 'checkbox', type_options: { disabled: true } }
          - { property: 'deployedAt', type: 'datetime' }
    User:
      class: App\Entity\User
      form:
        fields:
          - { property: 'username', type: 'text' }
          - { property: 'plainPassword', type: 'text', label: 'New password' }
          - { property: 'email', type: 'email' }
          - { property: 'hidden', type: 'checkbox', label: 'Account is disabled by user' }
          - 'roles'
