easy_admin:
  site_name: 'No Agenda Experience Administration Panel'
  design:
    menu:
      - { entity: 'Episode', icon: 'podcast', default: true }
      - { entity: 'ChatMessage', icon: 'comment' }
      - { entity: 'BatSignal', icon: 'signal' }
      - { entity: 'User', icon: 'user' }
  entities:
    BatSignal:
      class: App\Entity\BatSignal
      label: 'Bat signals'
      form:
        fields:
          - { property: 'code', type: 'text' }
          - { property: 'processed', type: 'checkbox', type_options: { disabled: true } }
          - { property: 'deployedAt', type: 'datetime' }
    ChatMessage:
      class: App\Entity\ChatMessage
      label: 'Chat messages'
      form:
        fields:
          - { property: 'username', type: 'text' }
          - { property: 'contents', type: 'textarea' }
    Episode:
      class: App\Entity\Episode
      label: 'Episodes'
      list:
        title: 'Episodes'
        sort: ['publishedAt', 'DESC']
        fields: ['code', { property: 'cover_uri', type: 'image', label: 'Cover' }, 'name', 'publishedAt', 'special']
      form:
        fields:
          - { property: 'code', type: 'text' }
          - { property: 'name', type: 'text' }
          - { property: 'author', type: 'text' }
          - { property: 'duration', type: 'integer' }
          - { property: 'published_at', type: 'date' }
          - { property: 'special', type: 'checkbox', label: 'Special episode' }
          - { property: 'chat_messages', type: 'checkbox', label: 'Episode has live chat messages' }
          - { property: 'transcript', type: 'checkbox', label: 'Episode has a transcript' }
          -
            type: 'section'
            icon: 'bug'
            label: 'Crawler data'
            help: 'Data used for crawling and processing metadata related to the show.'
          - { property: 'cover_uri', type: 'text' }
          - { property: 'recording_uri', type: 'text' }
          - { property: 'recorded_at', type: 'datetime', type_options: { widget: 'single_text', format: 'yyyy-MM-dd HH:mm:ss' } }
      edit:
        title: 'Edit episode'
      new:
        title: 'New episode'
    User:
      class: App\Entity\User
      label: 'Users'
      form:
        fields:
          - { property: 'username', type: 'text' }
          - { property: 'plainPassword', type: 'text', label: 'New password' }
          - { property: 'email', type: 'email' }
          - { property: 'hidden', type: 'checkbox', label: 'Account is disabled by user' }
          - 'roles'
