easy_admin:
  site_name: 'No Agenda Experience Administration Panel'
  design:
    menu:
      - { entity: 'Episode', label: 'Episodes', icon: 'podcast', default: true }
      - { entity: 'EpisodePart', label: 'Chapters', icon: 'bookmark' }
      - { entity: 'EpisodePartCorrection', label: 'Chapter corrections', icon: 'lightbulb-o' }
      - { entity: 'ChatMessage', label: 'Chat messages', icon: 'comment' }
      - { entity: 'User', label: 'Users', icon: 'user' }
      - { label: 'Network' }
      - { entity: 'NetworkSite', label: 'Network sites', icon: 'globe' }
      - { label: 'Processing' }
      - { route: 'admin_crawler', label: 'Crawler', icon: 'bug' }
      - { entity: 'BatSignal', label: 'Bat signals', icon: 'signal' }
      - { route: 'admin_livestream_recordings', label: 'Livestream recordings', icon: 'microphone' }
      - { route: 'admin_chat_logs', label: 'Chat logs', icon: 'comments' }
      - { label: 'Site' }
      - { route: 'homepage', label: 'Back to site', icon: 'door-open' }
