httplug:
    plugins:
        redirect:
            preserve_header: true
        retry:
            retry: 1

    discovery:
        client: 'httplug.client.app'

    clients:
        # Generic HTTP client
        app:
            factory: 'httplug.factory.guzzle7'
            http_methods_client: true
            plugins:
                - 'httplug.plugin.content_length'
                - 'httplug.plugin.redirect'
        # Optimized HTTP client for a Mastodon API
        mastodon:
            factory: 'httplug.factory.guzzle7'
            http_methods_client: true
            plugins:
                - 'httplug.plugin.content_length'
                - 'httplug.plugin.redirect'
                - add_host:
                      host: '%env(MASTODON_DOMAIN)%'
                - add_path:
                      path: /api/v1
                - header_defaults:
                      headers:
                          'Authorization': 'Bearer %env(MASTODON_ACCESS_TOKEN)%'
        # Optimized HTTP client for shownotes crawling which relies on not being redirected
        shownotes:
            factory: 'httplug.factory.guzzle7'
            http_methods_client: true
            plugins:
                - 'httplug.plugin.content_length'
