framework:
    http_client:
        scoped_clients:
            mastodon.client:
                base_uri: '%env(MASTODON_DOMAIN)%/api/v1/'
                headers:
                    'Authorization': 'Bearer %env(MASTODON_ACCESS_TOKEN)%'
            shownotes.client:
                base_uri: 'http://noagendanotes.com'
                max_redirects: 0
