# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
services:
    Liip\ImagineBundle\Imagine\Filter\FilterManager: '@liip_imagine.filter.manager'
    Liip\ImagineBundle\Service\FilterService: '@liip_imagine.service.filter'

liip_imagine:
    driver: 'imagick'
    twig:
        mode: 'lazy'
    loaders:
        covers:
            filesystem:
                data_root: '%env(APP_STORAGE_PATH)%/covers'
    filter_sets:
        cover_small:
            data_loader: covers
            jpeg_quality: 85
            png_compression_level: 8
            cache: ~
            filters:
                scale:
                    dim: [ 512, 512 ]
        cover_large:
            data_loader: covers
            jpeg_quality: 85
            png_compression_level: 8
            cache: ~
            filters:
                scale:
                    dim: [ 1024, 1024 ]

#when@test:
#    liip_imagine:
#        loaders:
#            covers:
#                filesystem:
#                    data_root: '%kernel.project_dir%'
