framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: 'doctrine://default'
                options:
                    queue_name: async
                    auto_setup: false
            crawler:
                dsn: 'doctrine://default'
                options:
                    queue_name: crawler
                    auto_setup: false
            failed:
                dsn: 'doctrine://default'
                options:
                    queue_name: failed
                    auto_setup: false

        routing:
            'App\Message\Crawl': crawler
            'App\Message\MergeUser': async
            'App\Message\PrepareEpisode': crawler

        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    -
                        dispatch_after_current_bus
                    -
                        doctrine_ping_connection
                    -
                        doctrine_close_connection
            crawling.bus:
                middleware:
                    -
                        dispatch_after_current_bus
                    -
                        doctrine_ping_connection
                    -
                        doctrine_close_connection
                    -
                        doctrine_transaction
