framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            crawler:
                dsn: 'doctrine://default'
                options:
                    queue_name: crawler
                    auto_setup: false
            failed:
                dsn: 'doctrine://default'
                options:
                    queue_name: failed
                    auto_setup: false

        routing:
            'App\Message\Crawl': crawler
            'App\Message\CrawlFile': crawler
            'App\Message\GenerateEpisodeReport': crawler
            'App\Message\PrepareEpisode': crawler
            'App\Message\PublishEpisode': crawler

        default_bus: crawler_bus
        buses:
            crawler_bus:
                middleware:
                    -
                        dispatch_after_current_bus
                    -
                        doctrine_ping_connection
                    -
                        doctrine_close_connection
                    -
                        doctrine_transaction
