monolog:
    channels:
        - crawler
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event", "!crawler"]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console", "!crawler"]
            crawler_console:
                type: console
                verbosity_levels:
                    VERBOSITY_QUIET: NOTICE
                    VERBOSITY_NORMAL: INFO
                    VERBOSITY_VERBOSE: DEBUG
                    VERBOSITY_VERY_VERBOSE: DEBUG
                channels: crawler
            crawler_file:
                type: stream
                path: "%kernel.logs_dir%/crawler.log"
                level: debug
                channels: crawler

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!crawler"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
            crawler_console:
                type: console
                verbosity_levels:
                    VERBOSITY_QUIET: NOTICE
                    VERBOSITY_NORMAL: INFO
                    VERBOSITY_VERBOSE: DEBUG
                    VERBOSITY_VERY_VERBOSE: DEBUG
                channels: crawler
            crawler_file:
                type: stream
                path: "%kernel.logs_dir%/crawler.log"
                level: debug
                channels: crawler
