monolog:
    channels:
        - crawler
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                level: debug
                channels: ["!event", "!crawler"]
                path: "%kernel.logs_dir%/%kernel.environment%.log"
            console:
                type: console
                channels: ["!event", "!doctrine", "!console", "!crawler"]
                process_psr_3_messages: false
            crawler_console:
                type: console
                channels: [crawler]
                verbosity_levels:
                    VERBOSITY_QUIET: NOTICE
                    VERBOSITY_NORMAL: INFO
                    VERBOSITY_VERBOSE: DEBUG
                    VERBOSITY_VERY_VERBOSE: DEBUG
            crawler_file:
                type: stream
                level: debug
                channels: [crawler]
                path: "%kernel.logs_dir%/crawler.log"

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                channels: ["!event"]
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
            nested:
                type: stream
                level: debug
                path: "%kernel.logs_dir%/%kernel.environment%.log"

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: rotating_file
                level: info
                channels: ["!crawler"]
                path: "%kernel.logs_dir%/application.log"
                max_files: 28
            console:
                type: console
                channels: ["!event", "!doctrine", "!crawler"]
                process_psr_3_messages: false
            crawler_console:
                type: console
                channels: [crawler]
                verbosity_levels:
                    VERBOSITY_QUIET: NOTICE
                    VERBOSITY_NORMAL: INFO
                    VERBOSITY_VERBOSE: DEBUG
                    VERBOSITY_VERY_VERBOSE: DEBUG
            crawler_file:
                type: rotating_file
                level: debug
                channels: [crawler]
                path: "%kernel.logs_dir%/crawler.log"
                max_files: 28

when@staging:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: rotating_file
                level: debug
                channels: ["!crawler"]
                path: "%kernel.logs_dir%/application.log"
                max_files: 28
            console:
                type: console
                channels: ["!event", "!doctrine", "!crawler"]
                process_psr_3_messages: false
            deprecation:
                type: rotating_file
                channels: [deprecation]
                path: "%kernel.logs_dir%/deprecation.log"
                max_files: 28
            crawler_console:
                type: console
                channels: [crawler]
                verbosity_levels:
                    VERBOSITY_QUIET: NOTICE
                    VERBOSITY_NORMAL: INFO
                    VERBOSITY_VERBOSE: DEBUG
                    VERBOSITY_VERY_VERBOSE: DEBUG
            crawler_file:
                type: rotating_file
                level: debug
                channels: [crawler]
                path: "%kernel.logs_dir%/crawler.log"
                max_files: 28
