twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['form_theme.html.twig']
    globals:
        analytics_id: '%env(ANALYTICS_ID)%'
        analytics_domain: '%env(ANALYTICS_DOMAIN)%'
        security_token: '%env(APP_SECURITY_TOKEN)%'
        vapid_key: '%env(VAPID_PUBLIC_KEY)%'

        recording_times:
            - [4, 11] # Thursday at 11:00 PT
            - [7, 11] # Sunday at 11:00 PT

        adam_email: 'adam@curry.com'
        adam_social: 'https://psyopshop.com/@adam'
        john_email: 'john@dvorak.org'
        john_social: 'https://noauthority.social/@john'
        donate_email: 'notes@noagendashow.net'

        artgenerator_url: 'https://noagendaartgenerator.com'
        artgenerator_artworks_url: 'https://noagendaartgenerator.com/artworks'
        codedmonkey_donate_url: 'https://www.codedmonkey.com/sponsor?project=noagenda'
        donate_url: 'https://www.noagendadonations.com'
        github_url: 'https://github.com/NoAgenda/website'
        knightring_url: 'https://www.noagendarings.com'
        meetups_url: 'https://noagendameetups.com'
        meetups_events_url: 'https://noagendameetups.com/events/list/'
        meetups_resources_url: 'https://noagendameetups.com/resources/'
        newsletter_signup_url: 'http://www.gitmonation.com/signup.htm'
        podcast_feed_url: 'https://feeds.noagendaassets.com/noagenda.xml'
        podcast_namespace_url: 'https://github.com/Podcastindex-org/podcast-namespace'
        podcastindex_url: 'https://podcastindex.org'
        podcastindex_apps_url: 'https://podcastindex.org/apps?appTypes=app'
        podcastindex_social_url: 'https://podcastindex.social'
        podcasting20_podcast_url: 'https://web.podfriend.com/podcast/podcasting-20'
        trollroom_url: 'https://noagenda.stream'
        value4value_url: 'https://value4value.info/'

        codedmonkey_url: 'https://noauthority.social/@woodstock'
        darreno_url: 'https://planetrage.social/@Darren'
        damejennifer_url: 'https://noauthority.social/@jennifer'
        davejones_url: 'https://podcastindex.social/@dave'
        drebscott_url: 'https://noauthority.social/@drebscott'
        sirbemrose_url: 'https://bemrose.social/ryan'
        voidzero_url: 'https://podcastindex.social/@voidzero'

when@test:
    twig:
        strict_variables: true
