version: "3.8"

services:
  app:
    build:
      context: .
      target: app
    image: ghcr.io/noagenda/website/app:${APP_TAG:-local}
    restart: unless-stopped
    tty: true
    #entrypoint: docker-php-entrypoint
    #command: php-fpm
    depends_on:
      - database
    volumes:
      - ./:/srv/www
      - public_media:/srv/www/public/media
    networks:
      - assets
      - database
      - http
      - php

  assets:
    build:
      context: .
      target: assets
    image: ghcr.io/noagenda/website/assets:${APP_TAG:-local}
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/srv/www
    networks:
      - assets

  chat_recorder:
    image: ghcr.io/noagenda/website/app:${APP_TAG:-local}
    restart: unless-stopped
    tty: true
    entrypoint: app-php-entrypoint
    command: bin/console record chat
    depends_on:
      - app
    volumes:
      - ./:/srv/www
    networks:
      - php

  crawler:
    image: ghcr.io/noagenda/website/app:${APP_TAG:-local}
    restart: unless-stopped
    tty: true
    entrypoint: app-php-entrypoint
    command: bin/console messenger:consume crawler --sleep 60 --time-limit 3600
    depends_on:
      - app
    volumes:
      - ./:/srv/www
      - public_media:/srv/www/public/media
    networks:
      - database
      - php

  database:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: InTheMorning
      MYSQL_DATABASE: noagenda
      MYSQL_USER: dudenamedben
      MYSQL_PASSWORD: dudettenamedbernadette
    ports:
      - "8034:3306"
    volumes:
      - ./docker/database/conf.d:/etc/mysql/conf.d
      - database_data:/var/lib/mysql
    networks:
      - database

  http:
    build:
      context: .
      target: http
    image: ghcr.io/noagenda/website/http:${APP_TAG:-local}
    restart: unless-stopped
    depends_on:
      - app
      - assets
    ports:
      - "8033:80"
    volumes:
      - ./:/srv/www
      - ./docker/nginx/app.conf.template:/etc/nginx/templates/app.conf.template
      - public_media:/srv/www/public/media
    networks:
      - http

  livestream_recorder:
    image: ghcr.io/noagenda/website/app:${APP_TAG:-local}
    restart: unless-stopped
    tty: true
    entrypoint: app-php-entrypoint
    command: bin/console record livestream
    depends_on:
      - app
    volumes:
      - ./:/srv/www
    networks:
      - php

  mail:
    image: mailhog/mailhog
    restart: unless-stopped
    ports:
      - "8035:8025"
    networks:
      - php

volumes:
  database_data:
  public_media:

networks:
  assets:
  database:
  http:
  php:
