version: "3.8"

services:
  queue_worker:
    image: ghcr.io/noagenda/website/app:${APP_TAG:-local}
    restart: unless-stopped
    tty: true
    entrypoint: app-php-entrypoint
    command: bin/console messenger:consume --sleep 30 --time-limit 3600 scheduler_crawler crawler async
    depends_on:
      - app
    volumes:
      - ./:/srv/app
      - public_media:/srv/app/public/media
    networks:
      - database
      - php
