version: '3'

services:
  app:
    build: .
    restart: unless-stopped
    tty: true
    working_dir: /srv/www
    volumes:
      - ./:/srv/www
    networks:
      - http
      - database

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: InTheMorning
      MYSQL_DATABASE: noagenda
      MYSQL_USER: dudenamedben
      MYSQL_PASSWORD: dudettenamedbernadette
    ports:
      - "8034:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - database

  http:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8033:80"
    volumes:
      - ./:/srv/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - http

networks:
  database:
  http:

volumes:
  dbdata:
    driver: local
