version: 2.1
orbs:
  docker: circleci/docker@1.5.0
jobs:
  build-and-test:
    executor:
      name: docker/docker
    steps:
      - setup_remote_docker:
          version: 19.03.13
      - checkout
      - run: docker-compose build
      - run: docker-compose up -d app database assets
      - run: docker exec -t project_app_1 bin/scripts/wait-for-app.sh
      - run: docker exec -t project_assets_1 yarn run test
      - run: docker exec -t project_app_1 php bin/phpunit
workflows:
    build-and-test:
      jobs:
        - build-and-test
