easy_admin:
  entities:
    ChatMessage:
      class: App\Entity\ChatMessage
      label: 'Chat Messages'
      form:
        fields:
          - { property: 'username', type: 'text' }
          - { property: 'contents', type: 'textarea' }
      list:
        title: 'Chat Messages'
      edit:
        title: 'Edit chat message'
      new:
        title: 'New chat message'
