easy_admin:
  entities:
    EpisodePart:
      class: App\Entity\EpisodePart
      label: 'Chapters'
      list:
        title: 'Chapters'
        sort: ['createdAt', 'DESC']
        actions: ['-delete']
        fields:
          -
            property: 'name'
            type: 'text'
          -
            property: 'starts_at'
            type: 'integer'
          -
            property: 'episode'
          -
            property: 'enabled'
            type: 'boolean'
          -
            property: 'created_at'
            type: 'datetime'
          -
            property: 'creator'
      form:
        actions: ['-delete']
        fields:
          -
            property: 'name'
            type: 'text'
          -
            property: 'starts_at'
            type: 'integer'
          -
            property: 'enabled'
          -
            property: 'episode'
          -
            property: 'creator'
      edit:
        title: 'Edit chapter'
      new:
        title: 'New chapter'
