easy_admin:
  entities:
    NetworkSite:
      class: App\Entity\NetworkSite
      list:
        title: 'Network Sites'
        fields:
          -
            property: 'name'
          -
            property: 'uri'
          -
            property: 'displayUri'
          -
            property: 'priority'
      form:
        fields:
          -
            property: 'name'
          -
            property: 'displayUri'
          -
            property: 'uri'
            type: 'url'
          -
            property: 'icon'
          -
            property: 'description'
          -
            property: 'priority'
