parameters:
  locale: 'en'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $httpClient: '@httplug.client.app'
      $shownotesClient: '@httplug.client.shownotes'

  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  App\Crawling\:
    resource: '../src/Crawling'
    exclude: '../src/Crawling/CrawlingLogger.php'
    calls:
      - ['setLogger', ['@App\Crawling\CrawlingLogger']]

  App\EventListener\Doctrine\:
    resource: '../src/EventListener/Doctrine'
    tags: ['doctrine.event_subscriber']

  Colorfield\Mastodon\MastodonAPI:
    factory: 'App\ApiFactory:mastodon'
    arguments:
      - '%env(MASTODON_AUTHORIZATION_CODE)%'
      - '%env(MASTODON_CLIENT_KEY)%'
      - '%env(MASTODON_CLIENT_SECRET)%'
      - '%env(MASTODON_ACCESS_TOKEN)%'

  #Rudolf\OAuth2\Client\Provider\Reddit:
  #  factory: 'App\ApiFactory:reddit'
  #  arguments:
  #    - '%env(REDDIT_CLIENT_KEY)%'
  #    - '%env(REDDIT_CLIENT_SECRET)%'
  #    - '%env(REDDIT_USERNAME)%'
  #    - '%env(REDDIT_PASSWORD)%'

  Liip\ImagineBundle\Imagine\Filter\FilterManager: '@liip_imagine.filter.manager'
  Liip\ImagineBundle\Service\FilterService: '@liip_imagine.service.filter'
