parameters:
  locale: 'en'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\:
    resource: '../src/*'
    exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  App\EventListener\Doctrine\:
    resource: '../src/EventListener/Doctrine'
    tags: ['doctrine.event_subscriber']
