parameters:
  locale: 'en'
  storage_path: '%kernel.project_dir%/%env(APP_STORAGE_PATH)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $projectPath: '%kernel.project_dir%'
      $storagePath: '%storage_path%'

  App\:
    resource: '../src/*'
    exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  App\EventListener\Doctrine\:
    resource: '../src/EventListener/Doctrine'
    tags: ['doctrine.event_subscriber']
