services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $crawlers: '@crawler_locator'
            $httpClient: '@http_client'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Crawling\:
        resource: '../src/Crawling/'
        exclude: '../src/Crawling/{CrawlingLogger.php,CrawlingResult.php,Shownotes}'
        calls:
            - ['setLogger', ['@App\Crawling\CrawlingLogger']]
        bind:
            $mastodonAccessToken: '%env(MASTODON_ACCESS_TOKEN)%'
            $mastodonAccountId: '%env(MASTODON_ACCOUNT_ID)%'
            $mastodonPublish: '%env(MASTODON_PUBLISH)%'
            $youtubeKey: '%env(YOUTUBE_KEY)%'
            $youtubePlaylistId: '%env(YOUTUBE_PLAYLIST_ID)%'
        tags: ['crawler']

    App\Crawling\CrawlingLogger:
        arguments: ['@monolog.logger.crawler']

    App\EventListener\Doctrine\:
        resource: '../src/EventListener/Doctrine/'
        tags: ['doctrine.event_subscriber']

    Minishlink\WebPush\WebPush:
        arguments:
            - VAPID:
                subject: '%env(VAPID_SUBJECT)%'
                privateKey: '%env(VAPID_PRIVATE_KEY)%'
                publicKey: '%env(VAPID_PUBLIC_KEY)%'
        calls:
            - setAutomaticPadding: [false] # https://github.com/web-push-libs/web-push-php#payload-length-security-and-performance

    crawler_locator:
        class: Symfony\Component\DependencyInjection\ServiceLocator
        arguments:
            - !tagged_iterator crawler

    Symfony\Bridge\Twig\Extension\AssetExtension: '@twig.extension.assets'
