easy_admin:
  site_name: 'No Agenda Experience Administration Panel'
  design:
    menu:
      - { entity: 'Episode', icon: 'podcast', default: true }
      - { entity: 'EpisodePart', icon: 'bookmark' }
      - { entity: 'EpisodePartCorrection', icon: 'lightbulb-o'  }
      - { entity: 'ChatMessage', icon: 'comment' }
      - { entity: 'User', icon: 'user' }
      - { label: 'Network' }
      - { entity: 'NetworkSite', label: 'Network Sites', icon: 'globe' }
      - { label: 'Processing' }
      - { entity: 'BatSignal', icon: 'signal' }
      - { route: 'admin_livestream_recordings', label: 'Livestream Recordings', icon: 'microphone' }
      - { route: 'admin_chat_logs', label: 'Chat Logs', icon: 'comments' }
