easy_admin:
  entities:
    EpisodeChapter:
      class: App\Entity\EpisodeChapter
      label: 'Chapter'
      list:
        title: 'Chapters'
        sort: ['createdAt', 'DESC']
        fields:
          -
            property: 'name'
            type: 'text'
          -
            property: 'starts_at'
            type: 'integer'
          -
            property: 'episode'
          -
            property: 'created_at'
            type: 'datetime'
          -
            property: 'creator'
      form:
        fields:
          -
            property: 'name'
            type: 'text'
          -
            property: 'starts_at'
            type: 'integer'
          -
            property: 'episode'
          -
            property: 'creator'
      edit:
        title: 'Edit chapter'
      new:
        title: 'New chapter'
