easy_admin:
  entities:
    Episode:
      class: App\Entity\Episode
      list:
        title: 'Episodes'
        sort: ['publishedAt', 'DESC']
        fields:
          -
            property: 'code'
            label: 'No.'
          -
            property: 'cover_uri'
            type: 'image'
            label: 'Cover'
          -
            property: 'name'
          -
            property: 'publishedAt'
          -
            property: 'special'
            type: 'boolean'
      form:
        fields:
          -
            property: 'code'
            type: 'text'
            label: 'Episode no.'
          -
            property: 'name'
            type: 'text'
          -
            property: 'author'
            type: 'text'
          -
            property: 'duration'
            type: 'integer'
          -
            property: 'published_at'
            type: 'date'
          -
            property: 'special'
            type: 'checkbox'
            label: 'Special episode'
          -
            property: 'chat_messages'
            type: 'checkbox'
            label: 'Episode has live chat messages'
          -
            property: 'transcript'
            type: 'checkbox'
            label: 'Episode has a transcript'
          -
            property: 'chat_notice'
            type: 'text'
          -
            type: 'section'
            icon: 'bug'
            label: 'Crawler data'
            help: 'Data used for crawling and processing metadata related to the show.'
          -
            property: 'cover_uri'
            type: 'text'
          -
            property: 'recording_uri'
            type: 'text'
          -
            property: 'recorded_at'
            type: 'datetime'
            type_options: { widget: 'single_text', format: 'yyyy-MM-dd HH:mm:ss' }
          -
            property: 'transcript_uri'
            type: 'text'
      edit:
        title: 'Edit episode'
      new:
        title: 'New episode'
