name: Run Project Tests

on: push

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build Docker Images
        run: docker-compose build --build-arg GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
      -
        name: Run JavaScript Tests
        run: docker run --entrypoint docker-entrypoint.sh ghcr.io/noagenda/website/assets:local npm run test
      -
        name: Run PHP Tests
        run: docker run ghcr.io/noagenda/website/app:local bin/phpunit
