name: Run Project Tests

on: push

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build Docker Images
        run: docker-compose build
      -
        name: Run JavaScript Tests
        run: docker-compose run assets npm run test
      -
        name: Run PHP Tests
        run: docker-compose run app bin/phpunit
